### PR TITLE
 Fix unnecessary index recreation due to algorithm option

### LINKED ISSUE #554: Index with `algorithm: :concurrently` causes constant DROP/CREATE on every run
When using `algorithm: :concurrently` option in `add_index` for PostgreSQL, ridgepole detects a difference on every run and attempts to DROP and recreate the index, even though the index already exists correctly in the database.

## Steps to Reproduce

1. Create a schema file with an index using `algorithm: :concurrently`:
```ruby
create_table "users", force: :cascade do |t|
  t.string "email", null: false
end

add_index "users", ["email"], name: "idx_users_email", algorithm: :concurrently
```
2. Apply the schema with ridgepole
3. Run ridgepole again without any changes
4. Ridgepole will show a diff and try to recreate the index

### Expected Behavior

Ridgepole should recognize that the index already exists and not attempt to recreate it.

### Actual Behavior

Ridgepole detects a difference and generates:
- DROP INDEX for the existing index
- CREATE INDEX CONCURRENTLY for the same index

### Root Cause

The algorithm option is only used during index creation (`CREATE INDEX CONCURRENTLY`) and is not stored in PostgreSQL's system catalog. When ridgepole compares the current database state with the schema file, it sees a difference because the database doesn't have the algorithm attribute.

### PR DESCRIPTION
**Pull request by ken39arg**
This PR fixes #554 where indexes with `algorithm: :concurrently` cause constant DROP/CREATE operations on every ridgepole run.

## Problem

The `algorithm: :concurrently` option is used only during index creation and is not stored in the database metadata. This caused ridgepole to detect false differences between the schema file and the actual database state.

## Solution

Modified the index comparison logic in `scan_indices_change` to exclude the `algorithm` option when comparing index definitions. The option is still preserved in the generated migration scripts to ensure `CREATE INDEX CONCURRENTLY` is used when creating new indexes.

## Changes

- Modified `lib/ridgepole/diff.rb` to ignore `algorithm` option during comparison
- Added test cases to verify the fix works correctly

## Testing

Added two test cases:
1. Verify that new indexes with `algorithm: :concurrently` are created correctly
2. Verify that existing indexes are not recreated when only the `algorithm` option differs

Run tests with:
```console
POSTGRESQL=1 bundle exec rspec spec/postgresql/diff/diff_spec.rb
```

in [cfd9e7b](https://github.com/ridgepole/ridgepole/pull/555/commits/cfd9e7b4898eab7a77ccabb073c41b89365964b8)
```console
$ POSTGRESQL=1 DEBUG=1 bundle exec rspec spec/postgresql/diff/diff_spec.rb
....F

Failures:

  1) Ridgepole::Client.diff when add index with algorithm: :concurrently when index exists without algorithm recreates index with algorithm: :concurrently
     Failure/Error: expect(delta).to_not be_differ
       expected `#<Ridgepole::Delta:0x0000000125411470 @delta={:change=>{"users"=>{:indices=>{:add=>{"idx_users_email"...alse, @mon_data=#<Monitor:0x000000011eb9cc78>, @mon_data_owner_object_id=4940>, @level_override={}>>.differ?` to be falsey, got true
     # ./spec/postgresql/diff/diff_spec.rb:272:in `block (4 levels) in <top (required)>'

Finished in 2.67 seconds (files took 0.48748 seconds to load)
5 examples, 1 failure

Failed examples:

rspec ./spec/postgresql/diff/diff_spec.rb:270 # Ridgepole::Client.diff when add index with algorithm: :concurrently when index exists without algorithm recreates index with algorithm: :concurrently
```

### CODE REVIEW

File: lib/ridgepole/diff.rb [hunk 1]
```diff
@@ -353,7 +353,11 @@ def scan_indices_change(from, to, to_columns, table_delta, _from_table_options,
           normalize_index_options!(from_attrs[:options])
           normalize_index_options!(to_attrs[:options])
 
-          if from_attrs != to_attrs
+          # Create copies for comparison, excluding algorithm option
+          to_attrs_for_compare = to_attrs.deep_dup
+          to_attrs_for_compare[:options]&.delete(:algorithm)
+
+          if from_attrs != to_attrs_for_compare
```
Comment (winebarrel) [inline lib/ridgepole/diff.rb:360]: Could you please fix it with the `normalize_index_options!` method?

```diff
diff --git a/lib/ridgepole/diff.rb b/lib/ridgepole/diff.rb
index ba4ff9e..74d6582 100644
--- a/lib/ridgepole/diff.rb
+++ b/lib/ridgepole/diff.rb
@@ -433,6 +433,8 @@ module Ridgepole
       # XXX: MySQL only?
       opts[:using] = :btree unless opts.key?(:using)
       opts[:unique] = false unless opts.key?(:unique)
+      # ... any foo bar comment ...
+      opts.delete(:algorithm)
     end
 
     def columns_all_include?(expected_columns, actual_columns, table_options)
```

**Review by winebarrel — CHANGES_REQUESTED** [review]
see https://github.com/ridgepole/ridgepole/pull/555/files#r2223156873

File: spec/postgresql/diff/diff_spec.rb [hunk 2]
```diff
@@ -213,4 +213,65 @@
...
+          end
+
+          add_index "users", ["email"], name: "idx_users_email", algorithm: :concurrently
+        RUBY
+      end
+
+      it 'creates index with algorithm: :concurrently' do
+        delta = subject.diff(actual_dsl, expected_dsl)
+        expect(delta).to be_differ
+        expect(delta.script).to match(/add_index\("users", \["email"\], .*algorithm.*concurrently.*\)/)
```
Comment (winebarrel) [inline spec/postgresql/diff/diff_spec.rb:244]:
```suggestion
        expect(delta.script).to match_ruby <<-RUBY
          add_index("users", ["email"], **{name: "idx_users_email", algorithm: :concurrently})
        RUBY
```

**Review by winebarrel — APPROVED** [review]

**Comment by winebarrel** [comment]
v3.0.3 has been released
